#######
POST https://localhost:5010/register HTTP/1.1
Content-Type: application/json

{
 "email": "bendahara@pus.com",
 "nama": "bendahara",
 "no_tlp": "081294262232",
 "password": "bendahara",
 "rePassword": "bendahara",
 "status_anggota": "3",
 "roles": "3"
}
#######
POST https://localhost:5010/login HTTP/1.1
Content-Type: application/json

{
 "email" : "ketua@pus.com",
 "password": "ketua"
}
#######
POST https://localhost:5010/logout HTTP/1.1
Content-Type: application/json

{
 "email" : "ketua@pus.com",
 "password": "ketua"
}
#######
POST https://localhost:5010/findAnggota HTTP/1.1
Content-Type: application/json

{
 "email" : "ketua@pus.com",
 "password": "ketua"
}
####
POST https://localhost:5010/perbaikanPinjamanTrans HTTP/1.1
Content-Type: application/json

{
 "email" : "ketua@pus.com",
 "password": "ketua"
}