name: Deploy API to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: 
      name: VPS HOST 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Debug and Deploy to VPS
      run: |
        echo "Port: '${{ secrets.VPS_PORT }}'"
        echo "Username: '${{ secrets.VPS_USERNAME }}'"
        echo "Host: '${{ secrets.VPS_HOST }}'"
        
        ssh -p "${{ secrets.VPS_PORT }}" -o StrictHostKeyChecking=no "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}" << 'EOF'
          cd /var/www/api.kkpus.id
          git pull origin master
        EOF